---
version: "2"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./public:/var/www/http
      - ./certs:/etc/certs
    ports:
      - "8888:80"
      - "443:443"
      - "442:442"
